name: Continuous Integration Testing

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
  API_TIMEOUT: ${{ secrets.API_TIMEOUT }}
  NODE_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate GraphQL types
        run: npm run generate

      - name: Run linter checks
        run: npm run lint

      - name: Run unit tests
        run: npm test
